### ISSUE TITLE
Create a system to handle user input

### ISSUE THREAD

**Issue by lavinrp** [AgreeableDeerGames/GameBackbone#234]
**Is your feature request related to a problem? Please describe.**
Every GB consumer must currently implement player controllers themselves.

**Describe the solution you'd like**
We can save time for every game built with GB by implementing a generic version here.
Design Goals:
*  generic enough to allow for different physical controllers (game pad, keyboard, etc...)
*  should allow for both setting default bindings
*  easy runtime overrides of bindings so that players can rebind.
* allow for different types of inputs (tap, press and hold)
    * preferably make it generic enough to allow for input types that we haven't thought of
* must be opt in. GB users should have the option of implementing this on their own.

We should change PlatformDemo (and perhaps all of our demos) to use this new controller.

# Implementation
* [x] Gesture Handler
  * Bindable gestures
    * Support maximum time between inputs
    * Consider supporting minimum time between inputs
  * Should be able to iterate through the gestures 
  * Should be able to retrieve individual gestures
  * Should be able to name gestures
* [x] InputRouter to facilitate joining multiple input handlers
* [X] Input Handler
  * Provide an interface for handling input
* [x] Input Filter
  * Provide a way of filtering out inputs before they are passed to a GestureHandler
  * Best place for this is probably template argument for BasicGestureBind
* [ ] ~Global Key Pressed Fetching~ (now tracked by #253)
  * ~Should be able to check if a bindable key is pressed~
  * ~Should be able to name bindings~
  * ~Should be able to iterate over bindings~
  * ~Should be able to get a specific binding~
  * ~Should be able to see if multiple keys are pressed at the same time~
* [x] Input Recorder
  * Provide a way of recording gestures / single key binds 
  * Dynamic event comparitor recorder support required
* [x] Bikeshed on names
* [x] Documentation

# Notes
* Make sure to handle template parameters that are not default constructable
* Update platform demo to use new system
* nodiscard and noexcept where necessary

# Gesture Test Cases
The below cases have 0 time between events

## Case 1
| gesture | bound action |
| :----: | :----: |
|  a -> b -> c ->d  | Action 1 |
| e | Action 2 |

User inputs:
`a -> b -> c -> e`

Result:
Action 2 is fired

## Case 2

Whats the desired behavior given this scenario:
| gesture | bound action |
| :----: | :----: |
|  a -> b  | Action 1 |
| c | Action 2 |

User inputs:
`a -> b -> c -> a -> b`

Result:
Action 1 Fires
Action 2 Fires
Action 1 Fires

## Case 3

Gestures have several end types
  1. Continuous
    * Fires with every subsequent event that matches the last event in the gesture
  2. Rest
    * Puts the gesture back to position 0 after it completes and allows the gesture to complete again
  3. Block
    * Fire the event and prevents it from firing while another event could consume the gesture
  4. Block Last Event
    * Fire the event and prevents it from firing until a event different from the last event in the gesture is fired or timeout

| gesture | bound action | End Type |
| :----: | :----: |:---:|
|  w  | Action 1 | Block |
| w -> w  | Action 2 | Block |
| w -> w -> w  | Action 3 | Block | 

User Inputs
`w -> w -> w`

Result:
Action 1 fires
Action 2 fires
Action 3 fires

## Case 3.1

| gesture | bound action  | End Type |
| :----: | :----: | :---: |
|  w  | Action 1 | Continuous |
| w -> w  | Action 2 | Continuous |
| w -> w -> w  | Action 3 | Continuous |

User Inputs
`w -> w -> w`

Result:
Action 1 fires
Action 1 fires
Action 2 fires
Action 1 fires
Action 2 fires
Action 3 fires

## Case 3.2

| gesture | bound action  | End Type |
| :----: | :----: | :---: |
|  w  | Action 1 | Stop |
| w -> w  | Action 2 | Reset |
| w -> w -> w  | Action 3 | Reset |

User Inputs
`w -> w -> w -> w -> w`

Result:
Action 1 fires
Action 2 fires
Action 3 fires
Action 2 fires

## Case 4
| gesture | bound action |
| :----: | :----: |
|  a -> b -> c ->d  | Action 1 |
| d | Action 2 |

User inputs:
`a -> b -> c -> d`

Result:
Action 1 fires
Action 2 does NOT fire

## Case 5
| gesture | bound action |
| :----: | :----: |
|  a -> b -> c   | Action 1 |

User inputs:
`a -> b -> a -> b -> c`

Result:
Action 1 fires 1 time

## Case 5.1
| gesture | bound action |
| :----: | :----: |
|  a -> b -> c   | Action 1 |
|  a  | Action 2 |

User inputs:
`a -> a -> b -> c`

Result:
Action 2 fires n times, Action 1 fires 1 time

## Case 5.2
| gesture | bound action |
| :----: | :----: |
|  a -> b -> c   | Action 1 |
|  a  -> b | Action 2 |

User inputs:
`a -> a -> b -> c`

Result:
Action 2 fires 1 time, Action 1 fires 1 time

**Comment by gyurgyma** [comment]
From the client issue:
"Likely an std::map <sf::key/sf::mouse/sf::joystick, std::function<bool(sf::event)>>
Should be something that can be set by someone somewhere. Maybe specialized, maybe a setter."

**Comment by gyurgyma** [comment]
https://www.sfml-dev.org/documentation/1.6/namespacesf_1_1Key.php
https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Mouse.php
https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Joystick.php

**Comment by lavinrp** [comment]
To enable things like QTEs make it possible to swap InputHandler instances on the fly or override what binds do things

**Comment by lavinrp** [comment]
Treat our input handler as a firewall between GB and SF inputs.
Something that will be very useful would be creating the concept of a cursor that is different than a mouse.

A game can have infinite cursors.

Users can bind different gestures to change the position of the cursor.

**Comment by lavinrp** [comment]
We will use a finite state automaton to produce the gesture that results from a set of user inputs.
The finite state automaton will be generated at runtime based on what bindings the user has created.

This will allow us to exit early after we hit a state that doesn't have any more options.

**Comment by lavinrp** [comment]
gestures that need data:
Cursor movement
Time between key presses?

**Comment by lavinrp** [comment]
# What we want
**If the user click three times:**
1st click: 
  * click event fires

2nd click: 
  * double click fires

3rd click: 
  * triple click fires

# What we dont want
**If the user click three times:**
1st click:
  * click event fires

2nd click
  * double click fires
  * click event fires

3rd click:
  * triple click fires
  * double click event fires 
  * click event fires

**Comment by lavinrp** [comment]
We can possibly use an "Open Set" algorithm for this.
Remove items from the open set if the input cannot be applied to them.
If the input cannot be applied to any item in the open set (and some items have already been removed from the open set) then reset the open set so that it includes all items and try again.

If nothing matches then take no action.

**Comment by lavinrp** [comment]
Consider this case:
| gesture | bound action |
| :----: | :----: |
|  a -> b -> c ->d  | Action 1 |
| e | Action 2 |
_____

User inputs:
a -> b -> c -> e

-----------
What should the output be?
Options:
1.  No action
    * a -> b -> c -> e is not a gesture so no action needed
    * works in editor like VS, but could be frustrating in a game where you dont want to take the time for the gesture to reset and start over
2. Action 2 is fired
    * Seems like the right solution for a game, but complicates implementation
    * Difficult to implement without the **What we dont want** from above

---------------

Possible solutions if we want to take the second option:
  * Only take actions out of the Open Set if they have fired. 
  * If action doesn't match key press just reset its progress back to 0


This brings up other questions though

Whats the desired behavior given this scenario:
| gesture | bound action |
| :----: | :----: |
|  a -> b  | Action 1 |
| c | Action 2 |

_____

User inputs:
a -> b -> c -> a -> b

-----------

Should action 1 fire twice even though the minimum time between gestures hasn't passed?
If finishing one gesture resets all other gestures then we get into a weird state with the following situation

| gesture | bound action |
| :----: | :----: |
|  w  | Action 1 |
| w -> w  | Action 2 |
| w -> w -> w  | Action 3 |

-----------

User Inputs

w -> w -> w

--------------

If all closed set gestures are opened after the completion of another gesture then the result of this would be:
Action 1, Action 2, Action 1, Action 3


------------

**Comment by lavinrp** [comment]
It seems to me like:
Case1
  * we want option 2
Case 2
  * We dont want Action 1 to fire twice
Case 3
  * no issue because of case 2

**Comment by lavinrp** [comment]
It needs to be possible to name a gesture bound by the InputHandler and look up / modify the gesture later.

Otherwise it will be difficult and inefficient to rebind.

**Comment by lavinrp** [comment]
No cool down timers

**Comment by lavinrp** [comment]
For Case 4 We should let user choose

**Comment by lavinrp** [comment]
First:
Case 4 seems broken

Second:
a b b b -> aciton 1
b b b   -> action 2
user inputs abbb

Do do both fire?
Is this covered by another case?
I dont think I see this above.

I'm on vacation at the airport.
I'll fix formatting in a few hours

**Comment by lavinrp** [comment]
For the second point I recall now that we decided that action 2 would not fire.
The same way VS doesn't launch the open file dialogue when the user presses ctrl + k, ctrl + o

**Comment by lavinrp** [comment]
> First:
> Case 4 seems broken
> 
> Second:
> a b b b -> aciton 1
> b b b -> action 2
> user inputs abbb
> 
> Do do both fire?
> Is this covered by another case?
> I dont think I see this above.
> 
> I'm on vacation at the airport.
> I'll fix formatting in a few hours

Turns out this whole thing was just from a typo on Case 4.
Case 4 has been fixed.

**Comment by lavinrp** [comment]
# Issue

A potential issue with Case 4 is if we create two binds to handle toggling a state (shift down to start sprinting and shift up to stop sprinting).

We could miss the key up event if another gesture is active when the user lets go of shift. The key up event would then cause the active gesture to fail and not cause the player to stop sprinting.

The player would then need to press shift again and release shift again to stop sprinting.

# Possible Solutions

1.  Provide a separate system for keys that need to be held down.
SFML has a way to check if an arbitrary key is currently pressed. We could abstract that so that the user can check if "sprint" is down instead of "shift"
1.  Make Case 4 somehow configurable so that the user can choose to make it always fire even if another gesture is active

**Comment by lavinrp** [comment]
Perhaps a series of handlers is in order?
one for gestures / key presses.
one for press and hold
one for mouse movement

That would also force us to be generic

**Comment by lavinrp** [comment]
If we make GestureBind a concept / interface then that can be the extension point on ButtonPressGestureHandler instead of the EventComparitor.

Our concrete implementation of GestureBind will have the extension point of EventComparitor.

**Comment by lavinrp** [comment]
Now that GestureBind is a type trait its really more generic than the name implies.
Same with ButtonPressGestureHandler.

We may be able to come up with names that better reflect their generality.
`using` statements to provide defaults for these template arguments would go a long way towards usability.

**Comment by lavinrp** [comment]
There is a bug where gesture bind can attempt to handle an even even when it is empty. This results in an assertion.
This can possibly be prevented by making readyForInput return false if the GestureBind is empty

**Comment by lavinrp** [comment]
An out of the box filter system will be required.

**Comment by lavinrp** [comment]
If we do input filtering at the BasicGestureBind level then it should be a template paramater like the EventComparator.
A processEvent call that has its input filtered should return {actionFired: false, readyForInput: [true/false], inputConsumed: false}.
the returned value for readyForInput should just be the normal result of readyForInput()

**Comment by lavinrp** [comment]
We need to do a [[nodiscard]] / constexpr / noexcept pass

**Comment by lavinrp** [comment]
Comparitor should be Comparator
https://docs.oracle.com/javase/7/docs/api/java/util/Comparator.html

**Comment by lavinrp** [comment]
QOL Improvement:
Template class where you can add a event comparitor and it will create public using statements for every layer above it.

**Comment by lavinrp** [comment]
Consider adding a builder pattern to generate the button press gesture handler.

**Comment by lavinrp** [comment]
@gyurgyma 
We should see what we can learn from this:
https://doc.qt.io/qt-5/qkeysequence.html

**Comment by lavinrp** [comment]
We plan to rename GestureBind to GestureMatchSignaler to make it clear that it is **matching** sequences of inputs and that it **signals** a slot when it finds a match.

**Comment by lavinrp** [comment]
ButtonPressGestureHandler -> ButtonGestureHandler

**Comment by gyurgyma** [comment]
Writing down for long term storage:
We should support asymmetric equals. So, If an event is on the left hand side of a comparison, it would be considered a "User" event, and thus the shift and ctrl keys would only matter if they are pressed down. Any event that is on the right would be considered a "System" event. This could mean that it's shift or ctrl are stronger.

I'm not sure I fully captured this, but think about these cases in relation to InputRecorder, ButtonPressGestureHandler, and GestureMatchSignaler. This has some strange relation to operator < being used to define operator = and even could be considered an operator = with subsets of each Gesture being comparable.

**Comment by gyurgyma** [comment]
Comments:
InputHandler:
	- Needs Commented.
InputRouter:
	- Detail namespace TODO
	- Detail namespace functions need commented
	- Should are_all_input_handlers_v be in InputHandler.h?
EventComparator:
	- Not Doxygen Comments
InputRecorder:
	- using statements should be (doxygen) commented?

**Comment by lavinrp** [comment]
CEC needs to store the time since the last call to handleEvent and reset this back to 0 after handleEvent gets called.

**Comment by lavinrp** [comment]
closed with https://github.com/AgreeableDeerGames/GameBackbone/pull/254
