### ISSUE TITLE
Release GB 0.4.0

### ISSUE THREAD

**Issue by lavinrp** [AgreeableDeerGames/GameBackbone#235]
- [x] Test Windows Build
- [x] Test Windows Unit Tests
- [x] Check Windows Warnings
- [x] Check Linux Build
- [x] ~Check Linux Unit Tests~
- [x] ~Check Linux Warnings~
- [x] Update version number in CMake
- [x] Update test consumer
- [x] Update User Manual
- [x] Update Consumer Template 
- [x] Update VCPKG

**Comment by gyurgyma** [comment]
This is ready to go, but Github Actions are being buggy right now. We are going to wait a day or so before we go ahead and release.

**Comment by lavinrp** [comment]
0.4.0 Released
