### ISSUE TITLE
Documentation for CompoundSprite variadic constructor is wrong

### ISSUE THREAD

**Issue by lavinrp** [AgreeableDeerGames/GameBackbone#241]
**Describe the bug**
Docs for CompoundSprite's variadic constructor are wrong.
They only mention two inputs. The constructor has three.

https://agreeabledeergames.github.io/GameBackbone/class_g_b_1_1_compound_sprite.html#a423d7033f38e7f77c0630ae38531a314

note that priority is missing from the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/8754600/80893622-1ac61080-8ca2-11ea-975f-9030044a866a.png)

**Comment by lavinrp** [comment]
Up for review: Branch feature/i241-CompSpriteDocs
I merged this issue with #244

**Comment by gyurgyma** [comment]
Reviewed and merged into dev.
