### ISSUE TITLE
CompoundSprite clearComponents should not be virtual

### ISSUE THREAD

**Issue by lavinrp** [AgreeableDeerGames/GameBackbone#244]
**Is your feature request related to a problem? Please describe.**
The storage of CompoundSprite is defined. There is really only one way to correctly clear its components.
**Describe the solution you'd like**
make CompoundSprite::clearComponents non-virtual

**Comment by lavinrp** [comment]
@gyurgyma 
While I'm here we have a rather odd line `(addComponent(priority, std::move(std::forward<Components>(componentsToAdd))), ...);`
Do you know if we did std::move(std::forward) for a reason?

**Comment by lavinrp** [comment]
Up for review: Branch feature/i241-CompSpriteDocs
I merged this issue with #241

**Comment by gyurgyma** [comment]
Reviewed and merged into dev.
